// Generated by CoffeeScript 1.9.1
(function() {
  describe('Dropbox', function() {
    return describe('#constructor', function() {
      return it('throws an Error pointing people to Dropbox.Client', function() {
        return expect(function() {
          return new Dropbox();
        }).to["throw"](Error, /Dropbox\.Client/);
      });
    });
  });

}).call(this);
