// Generated by CoffeeScript 1.9.1
(function() {
  describe('Web Worker tests', function() {
    if (typeof window !== 'undefined' && typeof window.Worker === 'function') {
      return it('pass', function(done) {
        var worker;
        this.timeout(3600000);
        worker = new Worker(window.location.href.replace(/\/html\/.*$/, '/js/helpers/web_worker_main.js'));
        worker.onmessage = function(event) {
          var message;
          message = event.data;
          switch (message.type) {
            case 'fail':
              return console.warn('WebWorker Test failed: ' + message.test.fullTitle);
            case 'done':
              expect(message).to.have.property('stats');
              expect(message.stats).to.have.property('failures');
              expect(message.stats.failures).to.equal(0);
              expect(message.stats).to.have.property('passes');
              expect(message.stats.passes).to.be.greaterThan(0);
              return done();
          }
        };
        worker.onerror = function(event) {
          console.warn(("WebWorker error: " + event.message + " ") + ("(" + event.filename + ": " + event.lineno + ")"));
          if (event.preventDefault) {
            return event.preventDefault();
          }
        };
        return worker.postMessage({
          type: 'go',
          testXhrServer: testXhrServer
        });
      });
    } else {
      return it.skip('pass');
    }
  });

}).call(this);
