// Generated by CoffeeScript 1.9.1
(function() {
  if (typeof window !== 'undefined') {
    mocha.setup({
      ui: 'bdd',
      slow: 150,
      timeout: 15000,
      bail: false,
      ignoreLeaks: !!window.cordova
    });
  } else {
    mocha.setup({
      ui: 'bdd',
      slow: 150,
      timeout: 15000,
      bail: false,
      reporter: 'post-message',
      ignoreLeaks: false
    });
  }

}).call(this);
