// Generated by CoffeeScript 1.9.1
(function() {
  var exports;

  exports = window;

  delete exports.testKeys['secret'];

  delete exports.testFullDropboxKeys['secret'];

  window.client = new Dropbox.Client(testKeys);

  console.log("Dropbox.Client instance exported as window.client");

}).call(this);
