// Generated by CoffeeScript 1.9.1
(function() {
  chrome.app.runtime.onLaunched.addListener(function() {
    return chrome.app.window.create('test/html/browser_test.html', {
      frame: 'chrome',
      id: 'browser_test',
      width: window.screen.availWidth,
      height: window.screen.availHeight
    });
  });

}).call(this);
