// Generated by CoffeeScript 1.9.1
(function() {
  var start, started;

  started = false;

  start = function() {
    if (started) {
      return;
    }
    chrome.tabs.create({
      url: 'test/html/browser_test.html',
      active: true
    });
    return started = true;
  };

  chrome.runtime.onStartup.addListener(start);

  chrome.runtime.onInstalled.addListener(start);

}).call(this);
