// Generated by CoffeeScript 1.9.1
(function() {
  var WebFileServer, buffer, exports, fs, i, testImagePath, webFileServer;

  require('source-map-support').install();

  exports = global;

  exports.Dropbox = require('../../../lib/dropbox');

  exports.chai = require('chai');

  exports.sinon = require('sinon');

  exports.sinonChai = require('sinon-chai');

  WebFileServer = require('./web_file_server.js');

  webFileServer = new WebFileServer();

  exports.testXhrServer = webFileServer.testOrigin();

  testImagePath = './test/binary/dropbox.png';

  fs = require('fs');

  buffer = fs.readFileSync(testImagePath);

  exports.testImageBytes = (function() {
    var j, ref, results;
    results = [];
    for (i = j = 0, ref = buffer.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      results.push(buffer.readUInt8(i));
    }
    return results;
  })();

  exports.assert = exports.chai.assert;

  exports.expect = exports.chai.expect;

}).call(this);
